// import React from 'react'
import { gifBG2 } from "../assets";
import { Input , Button} from "antd"
import  {Link} from "react-router-dom";

export default function Home() {
  return (
    <div className="max-w-7xl mx-auto">
        <div className="relative w-full h-[400px] lg:h-[550px] rounded-lg overflow-hidden shadow-lg">
            <img className="w-full h-full object-cover" src={gifBG2} alt="hero-bg" />
            <div className="absolute z-10 bg-gradient-to-t from-black from-70% opacity-50 w-full h-full top-0 left-0 text-white" />
            <div className="absolute z-10 top-0 left-0 w-full h-full flex flex-col text-white items-start pl-8 justify-center gap-4">
                <h1 className="font-extrabold text-[32px] !m-0">The Community Showcase</h1>
                <p className="text-[14px] max-w-[500px]">Browse through a collection of imaginative and visually stunning images generated by DALL-E AI</p>
                <Link to="/create-post" className='flex items-center gap-1'>
                  <Button className='bg-white h-10 hover:bg-gray-200 text-black font-semibold'>Create Image</Button>
                </Link>
            </div>
        </div>

        <div className="mt-14 flex flex-col gap-1 items-center justify-start">
            <p className="font-bold text-2xl uppercase">Gallery Images</p>
            <Input type="" placeholder="What do you looking for image" className="h-10"/>
        </div>
    </div>
  )
}
